const HtmlWebpackPlugin = require('html-webpack-plugin')

function createPage(template, filename) {
return new HtmlWebpackPlugin({
template: template,
filename: filename
})
}

const htmlPages = [
createPage('./src/index.html', './index.html'),
createPage('./src/pages/articles.html', './pages/articles.html'),
createPage('./src/pages/articles2.html', './pages/articles2.html'),
createPage('./src/pages/articles3.html', './pages/articles3.html'),
createPage('./src/pages/articles4.html', './pages/articles4.html'),
createPage('./src/pages/articles5.html', './pages/articles5.html'),
createPage('./src/pages/vzaim.html', './pages/vzaim.html'),
createPage('./src/pages/vzaim2.html', './pages/vzaim2.html'),
createPage('./src/pages/vzaim3.html', './pages/vzaim3.html'),
createPage('./src/pages/vzaim4.html', './pages/vzaim4.html'),
createPage('./src/pages/vzaim5.html', './pages/vzaim5.html'),
createPage('./src/pages/zvuk.html', './pages/zvuk.html'),
createPage('./src/pages/tests.html', './pages/tests.html'),

createPage('./src/articles/art1_1.html', './articles/art1_1.html'),
createPage('./src/articles/art1_2.html', './articles/art1_2.html'),
createPage('./src/articles/art1_3.html', './articles/art1_3.html'),
createPage('./src/articles/art1_4.html', './articles/art1_4.html'),
createPage('./src/articles/art1_5.html', './articles/art1_5.html'),
createPage('./src/articles/art1_6.html', './articles/art1_6.html'),
createPage('./src/articles/art1_7.html', './articles/art1_7.html'),
createPage('./src/articles/art1_8.html', './articles/art1_8.html'),
createPage('./src/articles/art1_9.html', './articles/art1_9.html'),

createPage('./src/articles2/art2_1.html', './articles/art2_1.html'),
createPage('./src/articles2/art2_2.html', './articles/art2_2.html'),
createPage('./src/articles2/art2_3.html', './articles/art2_3.html'),
createPage('./src/articles2/art2_4.html', './articles/art2_4.html'),
createPage('./src/articles2/art2_5.html', './articles/art2_5.html'),
createPage('./src/articles2/art2_6.html', './articles/art2_6.html'),
createPage('./src/articles2/art2_7.html', './articles/art2_7.html'),
createPage('./src/articles2/art2_8.html', './articles/art2_8.html'),
createPage('./src/articles2/art2_9.html', './articles/art2_9.html'),

createPage('./src/articles3/art3_1.html', './articles3/art3_1.html'),
createPage('./src/articles3/art3_2.html', './articles3/art3_2.html'),
createPage('./src/articles3/art3_3.html', './articles3/art3_3.html'),
createPage('./src/articles3/art3_4.html', './articles3/art3_4.html'),
createPage('./src/articles3/art3_5.html', './articles3/art3_5.html'),
createPage('./src/articles3/art3_6.html', './articles3/art3_6.html'),
createPage('./src/articles3/art3_7.html', './articles3/art3_7.html'),
createPage('./src/articles3/art3_8.html', './articles3/art3_8.html'),
createPage('./src/articles3/art3_9.html', './articles3/art3_9.html'),

createPage('./scr/development/1digital.html'),
createPage('./scr/development/2neuroacoustic.html'),
createPage('./scr/development/3integration.html'),
createPage('./scr/development/4vibration.html'),
createPage('./scr/development/5multimodal.html'),
createPage('./scr/development/6global.html'),

createPage('./scr/interview/interview1.html'),
createPage('./scr/interview/interview2.html'),
createPage('./scr/interview/interview3.html'),

createPage('./scr/meditation/1Sound_bath.html'),
createPage('./scr/meditation/2Mantra_maditation.html'),
createPage('./scr/meditation/3Binaural_rhythms.html'),
createPage('./scr/meditation/4Therapy_camberton.html'),
createPage('./scr/meditation/5Vocaal_toning.html'),
createPage('./scr/meditation/6Shamany_barabanenie.html'),
createPage('./scr/meditation/7m.html'),
createPage('./scr/meditation/8m.html'),
createPage('./scr/meditation/9m.html'),
createPage('./scr/meditation/10m.html'),

createPage('./scr/meditation_work'),

createPage('./scr/muzinst/1.html'),
createPage('./scr/muzinst/2.html'),
createPage('./scr/muzinst/3.html'),
createPage('./scr/muzinst/4.html'),
createPage('./scr/muzinst/5.html'),
createPage('./scr/muzinst/6.html'),
createPage('./scr/muzinst/7.html'),
createPage('./scr/muzinst/8.html'),
createPage('./scr/muzinst/9.html'),
createPage('./scr/muzinst/10.html'),
createPage('./scr/muzinst/11.html'),
createPage('./scr/muzinst/12.html'),
createPage('./scr/muzinst/13.html'),
createPage('./scr/muzinst/14.html'),
createPage('./scr/muzinst/15.html'),

createPage('./scr/people/Boris_Teplov.html'),
createPage('./scr/people/Christian_Huygens.html'),
createPage('./scr/people/Don_Campbell.html'),
createPage('./scr/people/Fabien_Maman.html'),
createPage('./scr/people/Mitch_Gayer.html'),
createPage('./scr/people/Petr_Anokhin.html'),
createPage('./scr/people/Tomatis_Alfred.html'),
createPage('./scr/people/Valeriy_Chkalov.html'),
createPage('./scr/people/Vladimir_Bechterev.html'),

createPage('./scr/tests/test1.html'),
createPage('./scr/tests/test2.html'),
createPage('./scr/tests/test3.html'),
createPage('./scr/tests/test4.html'),
createPage('./scr/tests/test5.html'),
createPage('./scr/tests/test6.html'),
createPage('./scr/tests/test7.html'),
createPage('./scr/tests/test8.html'),
createPage('./scr/tests/test9.html'),

// createPage(),
// createPage(),
// createPage(),
// createPage(),
// createPage(),
]

module.exports = htmlPages